### ISSUE TITLE
button tags

### ISSUE THREAD

**Issue by tulaeff** [cichy380/vue-plain-pagination#1]
Why do you use `button` tag here? Instead `a`. How I can change It? Bootstrap styles not work with `button` tag for me. Bootstrap 4

**Comment by cichy380** [comment]
Hi,

I used `<button>`, because this is not a link to some other page on website for me. It is button which make some action after click.

I am sorry, but configuration of tag type was not planned.

**Comment by tulaeff** [comment]
OK, but I can't use bootstrap styles with It

**Comment by cichy380** [comment]
You may have to add additional, custom styles specifically for these buttons.

Eg:
```scss
.pagination__btn {
   @extend .some-other-class;
}
```
